export const translations = {
  en: {
    appName: 'CivicCompanion',
    tagline: 'Your AI Government Portal',
    navHome: 'Dashboard',
    navReport: 'Report Issue',
    navTrack: 'Track Complaints',
    navSchemes: 'Public Schemes',
    navAccessibility: 'Accessibility Settings',
    
    // Companion
    companionTitle: 'AI Civic Assistant',
    companionSubtitle: 'Empathetic & agentic civic helper',
    companionPlaceholder: 'Ask a question or report an issue...',
    companionSpeechStart: 'Listening... Speak now.',
    companionSpeechStop: 'Stopped listening.',
    companionEmpty: 'Hello! I am your AI Civic Companion. Ask me about local benefits, help me report a pothole, or upload a document to verify eligibility.',

    // Dashboard
    dashGreeting: 'Hello Citizen',
    dashSubtitle: 'Welcome to your smart civic control panel. Choose a service below or talk to the AI Companion on the right.',
    dashAnnouncements: 'Recent Announcements',
    dashEmergencyContact: 'Emergency Dispatch',
    dashEmergencyDescription: 'For immediate risk of life or public safety hazards, call emergency services directly.',

    // Complaints
    compTitle: 'Public Issues & Safety Logs',
    compReportTitle: 'Submit a New Complaint',
    compTrackTitle: 'My Reported Tickets',
    compFieldTitle: 'Issue Summary (e.g. Broken Water Pipe)',
    compFieldDesc: 'Provide details about the issue...',
    compFieldLoc: 'Exact Location (Street / Landmark)',
    compFieldCat: 'Category',
    compFieldSev: 'Severity Check',
    compFieldPri: 'Priority Tier',
    compBtnSubmit: 'Register Complaint Ticket',
    compBtnUpdating: 'Filing Ticket...',
    compStatusSubmitted: 'Submitted',
    compStatusReview: 'Under Review',
    compStatusProgress: 'In Progress',
    compStatusResolved: 'Resolved',

    // Schemes
    schemeTitle: 'Demographic Scheme Matcher',
    schemeDesc: 'Enter your basic household demographics to evaluate matching government subsidies and grants instantly.',
    schemeFieldAge: 'Your Age',
    schemeFieldIncome: 'Annual Family Income ($)',
    schemeFieldHome: 'Do you own your home?',
    schemeFieldRes: 'Are you a legal city resident?',
    schemeBtnMatch: 'Analyze Scheme Eligibility',
    schemeMatchedHeader: 'Eligible Subsidies Found',
    schemeRequiredDocuments: 'Required Documents checklist',

    // Accessibility
    accTitle: 'Accessibility Customizations',
    accTextSize: 'UI Text Sizing',
    accSizeNormal: 'Normal Size',
    accSizeLarge: 'Large Text (125%)',
    accSizeHuge: 'Huge Text (150%)',
    accHighContrast: 'Forced High Contrast Theme',
    accVoiceSynthesis: 'AI Voice Narration (Text-to-Speech)',
    accReset: 'Reset to Defaults'
  },
  es: {
    appName: 'CivicCompanion',
    tagline: 'Su Portal de Gobierno AI',
    navHome: 'Tablero',
    navReport: 'Reportar Problema',
    navTrack: 'Seguimiento de Quejas',
    navSchemes: 'Subsidios Públicos',
    navAccessibility: 'Configuración de Accesibilidad',
    
    companionTitle: 'Asistente Cívico AI',
    companionSubtitle: 'Ayudante cívico empático y agéntico',
    companionPlaceholder: 'Haga una pregunta o reporte un problema...',
    companionSpeechStart: 'Escuchando... Hable ahora.',
    companionSpeechStop: 'Dejó de escuchar.',
    companionEmpty: '¡Hola! Soy su Compañero Cívico AI. Pregúnteme sobre beneficios locales, ayúdeme a reportar un bache o suba un documento para verificar elegibilidad.',

    dashGreeting: 'Hola Ciudadano',
    dashSubtitle: 'Bienvenido a su panel de control cívico inteligente. Elija un servicio a continuación o hable con el Asistente AI a la derecha.',
    dashAnnouncements: 'Anuncios Recientes',
    dashEmergencyContact: 'Despacho de Emergencias',
    dashEmergencyDescription: 'Para riesgo inmediato de vida o peligros de seguridad pública, llame a los servicios de emergencia directamente.',

    compTitle: 'Registro de Problemas Públicos y Seguridad',
    compReportTitle: 'Presentar una Nueva Queja',
    compTrackTitle: 'Mis Tickets Reportados',
    compFieldTitle: 'Resumen del Problema (ej. Tubería Rota)',
    compFieldDesc: 'Proporcione detalles sobre el problema...',
    compFieldLoc: 'Ubicación Exacta (Calle / Referencia)',
    compFieldCat: 'Categoría',
    compFieldSev: 'Verificación de Severidad',
    compFieldPri: 'Nivel de Prioridad',
    compBtnSubmit: 'Registrar Ticket de Queja',
    compBtnUpdating: 'Registrando Ticket...',
    compStatusSubmitted: 'Presentado',
    compStatusReview: 'Bajo Revisión',
    compStatusProgress: 'En Progreso',
    compStatusResolved: 'Resuelto',

    schemeTitle: 'Buscador de Subsidios Demográficos',
    schemeDesc: 'Ingrese los datos demográficos básicos de su hogar para evaluar los subsidios y subvenciones gubernamentales correspondientes al instante.',
    schemeFieldAge: 'Su Edad',
    schemeFieldIncome: 'Ingresos Familiares Anuales ($)',
    schemeFieldHome: '¿Es dueño de su casa?',
    schemeFieldRes: '¿Es residente legal de la ciudad?',
    schemeBtnMatch: 'Analizar Elegibilidad del Plan',
    schemeMatchedHeader: 'Subsidios Elegibles Encontrados',
    schemeRequiredDocuments: 'Lista de Documentos Requeridos',

    accTitle: 'Personalizaciones de Accesibilidad',
    accTextSize: 'Tamaño del Texto de la Interfaz',
    accSizeNormal: 'Tamaño Normal',
    accSizeLarge: 'Texto Grande (125%)',
    accSizeHuge: 'Texto Enorme (150%)',
    accHighContrast: 'Tema de Alto Contraste Forzado',
    accVoiceSynthesis: 'Narración de Voz AI (Texto a Voz)',
    accReset: 'Restablecer Valores Predeterminados'
  },
  hi: {
    appName: 'CivicCompanion',
    tagline: 'आपका एआई सरकारी पोर्टल',
    navHome: 'डैशबोर्ड',
    navReport: 'समस्या दर्ज करें',
    navTrack: 'शिकायत ट्रैकिंग',
    navSchemes: 'सरकारी योजनाएं',
    navAccessibility: 'एक्सेसिबिलिटी सेटिंग्स',
    
    companionTitle: 'एआई नागरिक सहायक',
    companionSubtitle: 'सहानुभूतिपूर्ण और सक्रिय नागरिक सहायक',
    companionPlaceholder: 'कोई प्रश्न पूछें या समस्या दर्ज करें...',
    companionSpeechStart: 'सुन रहा है... अब बोलें।',
    companionSpeechStop: 'सुनना बंद कर दिया।',
    companionEmpty: 'नमस्ते! मैं आपका एआई नागरिक साथी हूँ। मुझसे स्थानीय लाभों के बारे में पूछें, गड्ढे की रिपोर्ट करने में सहायता लें, या पात्रता की जांच के लिए दस्तावेज़ अपलोड करें।',

    dashGreeting: 'नमस्ते नागरिक',
    dashSubtitle: 'आपके स्मार्ट नागरिक नियंत्रण पैनल में आपका स्वागत है। नीचे दी गई सेवा चुनें या दाईं ओर एआई साथी से बात करें।',
    dashAnnouncements: 'हालिया घोषणाएं',
    dashEmergencyContact: 'आपातकालीन सेवा',
    dashEmergencyDescription: 'जीवन या सार्वजनिक सुरक्षा के तत्काल खतरे के लिए, आपातकालीन सेवाओं को सीधे कॉल करें।',

    compTitle: 'सार्वजनिक मुद्दे और सुरक्षा लॉग',
    compReportTitle: 'नई शिकायत दर्ज करें',
    compTrackTitle: 'मेरे दर्ज टिकट',
    compFieldTitle: 'समस्या का सारांश (जैसे: पानी का पाइप टूटना)',
    compFieldDesc: 'समस्या के बारे में विवरण प्रदान करें...',
    compFieldLoc: 'सटीक स्थान (सड़क / मील का पत्थर)',
    compFieldCat: 'श्रेणी',
    compFieldSev: 'गंभीरता जांच',
    compFieldPri: 'प्राथमिकता स्तर',
    compBtnSubmit: 'शिकायत टिकट पंजीकृत करें',
    compBtnUpdating: 'टिकट दर्ज किया जा रहा है...',
    compStatusSubmitted: 'जमा किया गया',
    compStatusReview: 'समीक्षाधीन',
    compStatusProgress: 'प्रगति पर है',
    compStatusResolved: 'सुलझाया गया',

    schemeTitle: 'जनसांख्यिकीय योजना मिलानकर्ता',
    schemeDesc: 'मिलान करने वाले सरकारी अनुदानों का तुरंत मूल्यांकन करने के लिए अपने परिवार की बुनियादी जनसांख्यिकी दर्ज करें।',
    schemeFieldAge: 'आपकी उम्र',
    schemeFieldIncome: 'वार्षिक पारिवारिक आय ($)',
    schemeFieldHome: 'क्या आपका अपना घर है?',
    schemeFieldRes: 'क्या आप कानूनी रूप से शहर के निवासी हैं?',
    schemeBtnMatch: 'योजना पात्रता का विश्लेषण करें',
    schemeMatchedHeader: 'योग्य सब्सिडी मिली',
    schemeRequiredDocuments: 'आवश्यक दस्तावेज़ों की सूची',

    accTitle: 'एक्सेसिबिलिटी अनुकूलन',
    accTextSize: 'यूआई टेक्स्ट का आकार',
    accSizeNormal: 'सामान्य आकार',
    accSizeLarge: 'बड़ा टेक्स्ट (125%)',
    accSizeHuge: 'अति बड़ा टेक्स्ट (150%)',
    accHighContrast: 'उच्च कंट्रास्ट थीम',
    accVoiceSynthesis: 'एआई आवाज वर्णन (टेक्स्ट-टू-स्पीच)',
    accReset: 'डिफ़ॉल्ट पर रीसेट करें'
  },
  fr: {
    appName: 'CivicCompanion',
    tagline: 'Votre Portail Cívique IA',
    navHome: 'Tableau de bord',
    navReport: 'Signaler un problème',
    navTrack: 'Suivi des réclamations',
    navSchemes: 'Subventions publiques',
    navAccessibility: 'Paramètres d\'accessibilité',
    
    companionTitle: 'Assistant Civique IA',
    companionSubtitle: 'Auxiliaire civique empathique et agentique',
    companionPlaceholder: 'Posez une question ou signalez un problème...',
    companionSpeechStart: 'Écoute en cours... Parlez maintenant.',
    companionSpeechStop: 'Écoute arrêtée.',
    companionEmpty: 'Bonjour! Je suis votre Compagnon Civique IA. Posez-moi des questions sur les subventions locales, aidez-moi à signaler un nid-de-poule, ou téléchargez un document pour vérifier votre éligibilité.',

    dashGreeting: 'Bonjour Citoyen',
    dashSubtitle: 'Bienvenue sur votre panneau de contrôle civique intelligent. Choisissez un service ci-dessous ou parlez à l\'Assistant IA à droite.',
    dashAnnouncements: 'Annonces Récentes',
    dashEmergencyContact: 'Service d\'urgence',
    dashEmergencyDescription: 'Pour un risque de vie imminent ou un danger de sécurité publique, contactez les services d\'urgence directement.',

    compTitle: 'Registre des Problèmes Publics & Sécurité',
    compReportTitle: 'Soumettre une Nouvelle Plainte',
    compTrackTitle: 'Mes Tickets Signalés',
    compFieldTitle: 'Résumé du problème (ex. Tuyau d\'eau cassé)',
    compFieldDesc: 'Fournissez des détails sur le problème...',
    compFieldLoc: 'Ubicación exacte (Rue / Point de repère)',
    compFieldCat: 'Catégorie',
    compFieldSev: 'Vérification de la sévérité',
    compFieldPri: 'Niveau de priorité',
    compBtnSubmit: 'Enregistrer le ticket de réclamation',
    compBtnUpdating: 'Enregistrement du ticket...',
    compStatusSubmitted: 'Soumis',
    compStatusReview: 'Sous révision',
    compStatusProgress: 'En cours',
    compStatusResolved: 'Résolu',

    schemeTitle: 'Calculateur d\'Éligibilité aux Subventions',
    schemeDesc: 'Entrez les données démographiques de base de votre foyer pour évaluer instantanément les subventions et aides gouvernementales disponibles.',
    schemeFieldAge: 'Votre Âge',
    schemeFieldIncome: 'Revenu Familial Annuel ($)',
    schemeFieldHome: 'Êtes-vous propriétaire de votre logement?',
    schemeFieldRes: 'Êtes-vous résident légal de la ville?',
    schemeBtnMatch: 'Analyser l\'Éligibilité au Régime',
    schemeMatchedHeader: 'Subventions Éligibles Trouvées',
    schemeRequiredDocuments: 'Liste des documents requis',

    accTitle: 'Personnalisations d\'Accessibilité',
    accTextSize: 'Taille du texte de l\'interface',
    accSizeNormal: 'Taille Normale',
    accSizeLarge: 'Grand Texte (125%)',
    accSizeHuge: 'Texte Énorme (150%)',
    accHighContrast: 'Thème à Contraste Élevé Forcé',
    accVoiceSynthesis: 'Narration Vocale IA (Synthèse Vocale)',
    accReset: 'Réinitialiser aux Valeurs par Défaut'
  }
};
export default translations;
